### ISSUE TITLE
Not giving any errors when using named imports incorrectly

### ISSUE THREAD

**Issue by saadq** [flowtype/ide-flowtype#16]
There does seem to be errors coming when using the module name incorrectly:

![screen shot 2017-09-12 at 7 04 37 pm](https://user-images.githubusercontent.com/5678694/30352359-78ea24b4-97ed-11e7-94ab-5ea01ba7d0b8.png)

However, there is no issue when there is a typo with the named import like `combineRedcers` here:

![screen shot 2017-09-12 at 7 04 58 pm](https://user-images.githubusercontent.com/5678694/30352375-8c2c4548-97ed-11e7-8ff5-133128e25122.png)

This is on macOS Sierra with Atom v1.20.0

**Comment by wbinnssmith** [comment]
hi @saadq! you should use [`flow-typed`](https://github.com/flowtype/flow-typed) to install type definitions for redux, and I believe then Flow should recognize these named exports.

Please re-open if this doesn't resolve your issue or you need clarification!

**Comment by saadq** [comment]
Ahh, apologies – not sure what happened there. Thanks for the quick reply.
