### ISSUE TITLE
Only run if .flowconfig present? (open to PRing!)

### ISSUE THREAD

**Issue by markthethomas** [flowtype/ide-flowtype#23]
Hey!

Love Flow and the ways the community is finding ways to tie it into Atom! I'd used Nuclide in the past but ended up moving away from it for various reasons, but was excited to try out the slightly-stripped down atom-ide! After installing that and then flow-ide and opening a non-flow project (i.e. lacking a .flowconfig), I got absolutely massive memory usage (~10-20GB). Figuring it was because it was including a huge node_modules folder and the lack of a `.flowconfig` wasn't telling flow not to parse those files. 

That part makes good sense, but I'm wondering if there would be a way to enable "run if .flowconfig" functionality for this package like I've seen in other atom packages (some eslint ones specifically)? Reason I ask is because not all of my work projects are using flow and committing a .flowconfig to some repos isn't really an option. But if there's an option to only run if a `.flowconfig` exists, people in my situation (i.e.g not using/in all flow-based projects) would be able to take advantage of this project more easily 👍 

Would be more than happy to PR and add the functionality in, but wanted to see if there was something I'm missing first 👍  thanks!

**Comment by markthethomas** [comment]
Oh interesting! I wonder if it's the deeper flowconfig, I might have one of those floating around somewhere. It was definitely flow, can confirm via experience (only after install, fans kick in, everything crawls to stop, other apps suspended to preserve memory) and then via activity monitor. It would make sense that it would be overwhelmed if I have a flowconfig in my home dir, I'll check that out 👍 thanks for replying!

**Comment by markthethomas** [comment]
yep, that's the culprit! Thanks again @wbinnssmith! 👌 

<img width="133" alt="screen shot 2017-09-14 at 11 41 27 am" src="https://user-images.githubusercontent.com/4926721/30447740-c7a41aa6-9941-11e7-970b-15983cb46bb1.png">
<img width="701" alt="screen shot 2017-09-14 at 11 41 52 am" src="https://user-images.githubusercontent.com/4926721/30447741-c7a9e166-9941-11e7-93b3-a460368f452b.png">

**Comment by wbinnssmith** [comment]
Good to see this is resolved! I imagine this isn't an uncommon situation though, so we should probably figure a way of letting the user know.

Thing is, it's also not uncommon to mount a subdirectory of your flow root as a root within Atom, and users would probably expect flow to work in those situations :\
