### ISSUE TITLE
Support JSX for React.js projects

### ISSUE THREAD

**Issue by VladimirPesterev** [flowtype/ide-flowtype#33]
Is it planned to support JSX React.js projects and how can i help?

**Comment by Cerberus** [comment]
It's already support React Component.

If you write a stateful component, the code is look like this
```jsx
class Test extends React.Component<Props> {
```

Stateless component with enhance Function can be written like this
```jsx
import { type HOC, compose, lifecycle, mapProps, pure } from 'recompose'
import React from 'react'

type Common = {
	className?: string,
}

type Enhanced = {
	a: boolean,
	b: boolean,
	show: boolean,
} & Common

type Props = {} & Common

const enhance: HOC<Props, Enhanced> = compose(
	lifecycle({}),
	mapProps(({ ...rest }) => ({ ...rest })),
	pure,
)

export const Test = ({ className }: Props) => (
	<div className={className}>
		<span />
	</div>
)

export default enhance(Test)

```

Type checking work normally like other packages.

To make autocomplete, you need to type at least 3 characters to active hint tooltip. (Custom Minimum word length on autocomplete-plus core package)

<img width="533" alt="auto" src="https://user-images.githubusercontent.com/9087409/41672148-76843740-74e3-11e8-9595-2960c6924d36.png">

Shall we close this? 😄

**Comment by VladimirPesterev** [comment]
Yes, now the current version supports jsx. Thnx
