### ISSUE TITLE
Changes to flow-typed library definition are not recognized

### ISSUE THREAD

**Issue by mattcollier** [flowtype/ide-flowtype#49]
In my project I have established a `flow-typed` folder and a single file `global.js` in there where I am defining some globals and modules as described here: https://flow.org/en/docs/libdefs/creation/

My expectation is that if I make a change to `global.js`, return to my application file and save to kick-off the linter that my changes to `global.js` would be recognized and applied.  

What I'm finding is that I must reload the window (Ctrl+Shift+F5) to get the new `global.js` definitions into effect.

Atom 1.23.1
OS: Debian 9

**Comment by rpowelll** [comment]
I've noticed the same issue on macOS 10.13.2 with Atom 1.23.2

**Comment by mattcollier** [comment]
I've determined that one must add the `// @flow` annotation to library definitions in the `flow-typed` folder for them to be watched.  Filed issue here: https://github.com/facebook/flow/issues/5625

Closing this one.

**Comment by MathMesquita** [comment]
I'm having this issue yet...

The global types only work if the libdef file is open on another tab in the editor.
