### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by deankevorkian** [flowtype/ide-flowtype#55]
It seems like the [flow-language-server](https://github.com/flowtype/flow-language-server) doesn't state there's no Windows support (anymore).  As for [this PR](https://github.com/flowtype/flow-language-server/pull/58) as well, seems like Windows support has been merged to the LS (which ide-flowtype now uses).
So is windows support here for ide-flowtype as well? (as the server supports it now)? README still mentions no windows support.

**Comment by Arcanemagus** [comment]
See my (identically titled 😆) issue: https://github.com/flowtype/ide-flowtype/issues/42

tl;dr it _should_ be working now, and if the `README.md` states otherwise you might want to send in a PR fixing that 😉.

**Comment by deankevorkian** [comment]
Oh right. should've checked for a closed issue first 🤦‍♂️ 
I'll send a PR fixing this :)
