### ISSUE TITLE
Installation failed: Not found

### ISSUE THREAD

**Issue by jzimmek** [flowtype/ide-flowtype#6]
Hi,

I tried to install this package a couple of times in the last few days but it always fail with the following error:

```
apm install ide-flowtype
Installing ide-flowtype to /Users/jzk/.atom/packages ✗
Request for package information failed: Not Found
```

The atom-ide-ui is already installed without any problems.

The package "ide-flowtype" also do not appear as a result when I search in atom.

Atom: 1.18.0 x64
macOS: 10.12.6

**Comment by wbinnssmith** [comment]
Looks like you happened to try to install it between the time I updated the README and the time I published. I should have done that the other way around :P

Anyway, try installing again (same instructions) but it should work this time!

Hope you enjoy ide-flowtype and feel free to re-open if you encounter any issues :)
