### ISSUE TITLE
Where are the global Atom types coming from?

### ISSUE THREAD

**Issue by saadq** [flowtype/ide-flowtype#62]
I noticed that there seems to be autocomplete suggestions coming for the `atom` global variable, even when all I have in my `atom.js` decls is `declare var atom: Object`

![screen shot 2018-02-23 at 4 10 25 pm](https://user-images.githubusercontent.com/5678694/36617089-2b83e12c-18b4-11e8-9523-7886a0281785.png)

I'm mainly asking because when I write my own types, I'm unable to get descriptions of the types appear at the bottom of the autocomplete window like they do in the screenshot. Just wanted to see if there's a certain syntax you need to use for comments to show up in the autocomplete suggestion.

I tried looking through both `atom-ide-ui` and `ide-flowtype`, but I don't think I was able to find where the descriptions were coming from.

**Comment by Arcanemagus** [comment]
The built in Atom API autocompletions are coming from [autocomplete-atom-api](https://github.com/atom/autocomplete-atom-api).

**Comment by saadq** [comment]
Ah, apologies for opening the issue here. Hadn't really noticed this til I started using flowtype.
