### ISSUE TITLE
Autocomplete suggestion priority overrides snippets

### ISSUE THREAD

**Issue by nfarina** [flowtype/ide-flowtype#65]
Hi! Loving `ide-flowtype`.

I've noticed that `ide-flowtype` is setting a `suggestionPriority` of `5` here:

   https://github.com/flowtype/ide-flowtype/blob/master/lib/main.js#L122

This would be OK except that it overrides the built-in `autocomplete-snippets` priority of `2`. This means that when you're quickly typing code using snippets, your snippets are often "buried" in the list somewhere.

Common example: there is a `log` snippet where you can type `log` followed by `tab` and it expands to `console.log()`. But, when `ide-flowtype` is in use, you often get other flow-related completions instead:

<img width="204" alt="screen shot 2018-03-20 at 9 19 17 am" src="https://user-images.githubusercontent.com/117280/37672372-08de193c-2c2b-11e8-9fb3-4bafbca9abee.png">

The end result is that typing `log+tab` almost never results in your desired snippet. It really handicaps the utility of snippets, as evidenced by a few open issues ([#88](https://github.com/atom/autocomplete-snippets/issues/88), [#946](https://github.com/atom/autocomplete-plus/issues/946), [#157](https://github.com/facebook-atom/atom-ide-ui/issues/157)) across various repos.

I'm wondering why the value of `5` was chosen for Flow's completion suggestions? When I change it to, for instance, `1`, I get a more correct ordering:

<img width="204" alt="screen shot 2018-03-20 at 10 34 28 am" src="https://user-images.githubusercontent.com/117280/37672409-208cdbcc-2c2b-11e8-8696-89d56a9bcd58.png">

And Flow's suggestions are still given priority over the "dumb" word-in-file completions provided by Atom out of the box.

Would a PR modifying the priority back to `1` be considered?

**Comment by saadq** [comment]
There's a [pull request](https://github.com/flowtype/ide-flowtype/pull/60) open to allow configuration of the autocomplete priority which would be nice.

**Comment by nfarina** [comment]
Looks like it got merged, closing this, thanks! 🎉
