### ISSUE TITLE
Keyword colors

### ISSUE THREAD

**Issue by Extarys** [flowtype/ide-flowtype#66]
Would it be possible to color no-cap keywords? I really don't know how plugins works so maybe ide-flowtype can't.

![1-flow-nocolor](https://user-images.githubusercontent.com/11581433/39404769-94720962-4b67-11e8-9bbc-cfca320b550d.png)

![2-flow-color](https://user-images.githubusercontent.com/11581433/39404770-948136b2-4b67-11e8-9dca-f574db14eb3e.png)

**Comment by wbinnssmith** [comment]
hi @Extarys, this coloring is the job of the syntax package and not of ide-flowtype. Check out https://atom.io/packages/language-babel -- I believe it does what you're looking for.

**Comment by Extarys** [comment]
Thanks! I'll check it out
