### ISSUE TITLE
not working .vue file

### ISSUE THREAD

**Issue by arszp10** [flowtype/ide-flowtype#7]
for .js file correct working, but .vue file not working
this image that for .vue file
![image](https://user-images.githubusercontent.com/12972343/28997597-33d7fca0-7a21-11e7-9de2-ac1bf3592c55.png)
in .js file will work
![image](https://user-images.githubusercontent.com/12972343/28997612-77b0cc68-7a21-11e7-8119-6159bbe777e9.png)
![image](https://user-images.githubusercontent.com/12972343/28997625-d0161944-7a21-11e7-8c64-57773ae491b9.png)

**Comment by wbinnssmith** [comment]
hi @arszp10,

does Flow support these vue component files? We can add the `.vue` extension as a trigger to launch the package, but from what I can tell Flow does not ordinarily pick up on flow pragmas inside these script tags in the vue component file.

If you can get the commandline Flow to work with a vue project, please send me an example and I'll see what I can do to support it!
