### ISSUE TITLE
Atom selects wrong language for all flow files

### ISSUE THREAD

**Issue by Arilas** [flowtype/ide-flowtype#74]
For all files with `@flow` annotation Atom selects `Flow JavaScript` language that doesn't work with this plugin.

When I manually switch to `JavaScript` everything works, but it's impossible to do this every time when I open the file.

So I have:
1. 1.32.0 x64
2. Debian 8
3. Flow 0.82
4. Plugins: `atom-ide-ui@0.13.0` and `ide-flowtype@0.23.1` 

Steps to reproduce:
1. Clean installation of Atom
2. Install my plugins
3. Open any file with annotation `/** @flow */`

**Comment by mostafaeweda** [comment]
That’s caused by treesitter grammars (that’s enabled by default in Atom 1.32).

Please change Atom settings (uncheck using Treesitter Grammars)

**Comment by joshhepworth** [comment]
I ended up here because flow in the UI broke completely with 1.32.1 – for other that come here it seems as though disabling Tree-Sitter made the flow errors show up in the UI again.
