### ISSUE TITLE
This should be maintained

### ISSUE THREAD

**Issue by ryanolsonx** [flowtype/ide-flowtype#78]
https://github.com/atom/atom-languageclient is still maintained. Even though Atom IDE is not going to be officially supported anymore, that doesn't mean it's going to be gone.

**Comment by saadq** [comment]
Facebook most likely won't be maintaining it anymore as they mentioned in their deprecation notice, so it would probably be up to the community to fork this package and maintain it.

There's also the [flow-ide](https://github.com/steelbrain/flow-ide/) package which seems a bit more maintained.
